# Generated by Django 4.0.5 on 2022-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_address_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='username',
        ),
    ]
